### PR TITLE
Support custom function signatures

### PR DESCRIPTION
**Pull request by yperess**
Add support for other function signature types (like std::function and pw::Function)

### CODE REVIEW

**Comment by yperess** [comment]
I added an update to the documentation for the new feature

**Comment by meekrosoft** [comment]
This test seems to fail on my laptop:
image

**Comment by yperess** [comment]
@meekrosoft all the tests are passing now, thoughts?

**Comment by yperess** [comment]
@meekrosoft I've updated the PR to use the same include path in Windows as in MacOS and Linux (this makes things more consistent). I also included a link to the bug that's causing this problem.

**Comment by yperess** [comment]
@meekrosoft my DMs don't seem to be getting through for some reason. Zephyr's cutoff for features is coming up in 7 days (https://github.com/zephyrproject-rtos/zephyr/wiki/Release-Management#release-milestone-dates). I would like to get this feature merged and pulled into Zephyr by then otherwise it'll be locked until the end of the month).

**Pull request merged**
