### PR TITLE
Fix unreachable return statements.

### LINKED ISSUE #81: Unreachable return statements in commit 7e09f07e
**Describe the bug**
Unreachable return statements where introduced in commit 7e09f07e5b262b1cc826189dc5057379e40ce886.

**To Reproduce**
Goto fff.h, line 1657
See return statement which is unreachable, since the existence of return statement one line above.
This is only the example the same issue is copy pasted to multiple places where DEFINE_FAKE_VALUE_FUNCX is defined.

### PR DESCRIPTION
**Pull request by damaki**
This fixes #81 where some return statements that were generated unconditionally, leading to unreachable return statements.

### CODE REVIEW

**Comment by tiringjoel** [comment]
When will this pull request be completed? 
Our cppCheck currently fails because of the unreachable return statements. Would highly appreciate it.

**Comment by henrik-nil-acc** [comment]
@meekrosoft , please merge this, thanks

**Comment by shlomnissan** [comment]
@meekrosoft Any particular reason this wasn't merged in?

**Comment by wulfgarpro** [comment]
LGTM

**Pull request merged**
