### PR TITLE
Adding a section explaining how to fake variadic functions

### PR DESCRIPTION
**Pull request by rubiot**
This commit adds a new section to the README explaning how to fake variadic functions and how to access variadic parameters from a custom fake function.

### CODE REVIEW

**Comment by usr42** [comment]
Wow, that was fast.
I like this pull request for #29. Thank you very much!

**Comment by gatzka** [comment]
Would be great to have that included. I just stumbled around exactly this problem.

**Comment by usr42** [comment]
@meekrosoft Could this be merged?

**Comment by meekrosoft** [comment]
Yes, great!  Thanks for the contribution!

**Pull request merged**
