### PR TITLE
Fix for issue 13: Add function prototype to DECLARE_* macro

### PR DESCRIPTION
**Pull request by usr42**
This is a fix for [issue 13](https://github.com/meekrosoft/fff/issues/13).
The function prototype is added to the DECLARE_* macros.

I hope this change is ok for you, because I am not sure if you intentionally did not add the function prototype to the DECLARE_* macros.

Cheers,
Balthasar

### CODE REVIEW

**Comment by usr42** [comment]
@meekrosoft I just solved the merge conflicts.

**Comment by gatzka** [comment]
Would be nice to have that merged. I stumbled over the same problem.

**Comment by usr42** [comment]
@meekrosoft Can this PR be merged? Should anything be changed before?

**Comment by meekrosoft** [comment]
The main reason why I don't add the function prototype is that is usually already defined in a header.  I guess there is no harm in automatically add the prototype though.  Thanks for the contribution @usr42 !

**Pull request merged**
